config/routes.rb
Rails.application.routes.draw do
  resources :items

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :users, only: :show
  
  resources :lists

  root 'application#home'
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :lists
  has_many :items
  belongs_to :user
  
  validates_presence_of :title
  
  
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @new_item = Item.new()
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:title, :description, :user_id)
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit, class: 'form-control' %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lists</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.title %></td>
        <td><%= list.description %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<div class="col-md-6">
  <h2><%= @list.title %></h2>
  <h4><%= @list.description %></h4>
  <hr/>
  <div id="lister">
 
    <div class="col-md-6">
      <label>Search:</label><input class="search form-control"><br/>
    </div>
    <div class="col-md-12">
      <ul class="list">
	<% @list.items.each do |item| %>
	  <li class='list_item'><div class="title"><%= item.title %></div></li>
	<% end %>
      </ul>
    </div>
  </div>
</div>

<div class="col-md-4 col-md-offset-2">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3>Add Item</h3>
    </div>
    <div class="panel-body">
      <%= form_for(@new_item) do |i| %>
	<div class="field">
	  <%= i.label :title %><br>
	  <%= i.text_field :title, class: 'form-control'%>
	</div>
	<%= hidden_field_tag 'item[user_id]', current_user.id%>
	<%= hidden_field_tag 'item[list_id]', @list.id%>
	<div class="actions">
	  <%= i.submit 'Create', class: 'btn btn-success' %>
	</div>
      <% end %>
    </div>
  </div>

</div>
<div class="col-md-12">
  <%= link_to 'Edit', edit_list_path(@list) %> |
  <%= link_to 'Back', lists_path %>
</div>

<script type='text/javascript'>
  $(window).load(function(){
    var options = { valueNames: ['title'], page: 200};
    var titleList = new List("lister", options);
  });
</script>