config/routes.rb
Rails.application.routes.draw do
  resources :items

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :users, only: :show
  
  resources :lists

  root 'application#home'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :lists
  has_many :items
  
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    if verify_recaptcha
      super
    else
      build_resource(sign_up_params)
      clean_up_passwords(resource)
      flash.now[:alert] = "There was an error with the recaptcha code below. Please re-enter the code."      
      flash.delete :recaptcha_error
      render :new
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # You can put the params you want to permit in the empty array.
  def configure_sign_in_params
    devise_parameter_sanitizer.for(:sign_in) << :attribute
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
require 'gravatar'
class UsersController < ApplicationController
  before_filter :authenticate_user!
  def show
    @user = User.find(current_user.id)
    @gravatar_url = Gravatar.new.url(@user)
    @new_list = List.new()
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="col-lg-3">
  <div class="row"> 
    <div class="col-lg-12">
      <%= image_tag @gravatar_url, class: "img-rounded" %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <h4><%=@user.email%></h4>
      <p><b>Joined:</b> <%= @user.created_at.strftime('%B %d %Y')%></p>
      <%= link_to "Edit Username/Password", edit_user_registration_path, method: :get%>
    </div>
  </div>
</div>
<div class="col-lg-5">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3>My lists</h3>
    </div>
    <div class="panel-body">
      <div id="user_lists">
        <input class="search form-control"><br/>
	<ul class="list">
	  <% current_user.lists.each do |list|%>
	    <li class="list_item">
	      <%= link_to list.title, list_path(list), title: (list.description.nil? ? '' : list.description), class: 'title'%>
	    </li>
	  <%end%>
	</ul>
      </div>
    </div>
  </div>
</div>
<div class="col-lg-4">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3>Create a List!</h3>
    </div>
    <div class="panel-body">
      <%= form_for(@new_list) do |f| %>
	<div class="field">
	  <%= f.label :title %><br>
	  <%= f.text_field :title, class: 'form-control'%>
	</div>
	<div class="field">
	  <%= f.label :description %><br>
	  <%= f.text_area :description, class: 'form-control' %>
	</div>
	<%= hidden_field_tag 'list[user_id]', current_user.id%>
	<div class="actions">
	  <%= f.submit 'Create', class: 'btn btn-success' %>
	</div>
      <% end %>

    </div>
  </div>
</div>
<script type='text/javascript'>
  $(window).load(function(){
    var options = { valueNames: ['title'], page: 20};
    var titleList = new List("user_lists", options);
  });
</script>